package com.btbs.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Account.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Account implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** AccountID. */
	private Integer accountid;

	/** FullName. */
	private String fullname;

	/** Email. */
	private String email;

	/** Password. */
	private String password;

	/** Phone. */
	private Integer phone;

	/** Role. */
	private String role;

	/** Status. */
	private String status;

	/** CreatedAt. */
	private Date createat;

	/** The set of Booking. */
	private Set<Booking> bookingSet;

	/** The set of Wallet. */
	private Set<Wallet> walletSet;

	/**
	 * Constructor.
	 */
	public Account() {
		this.bookingSet = new HashSet<Booking>();
		this.walletSet = new HashSet<Wallet>();
	}

	/**
	 * Set the AccountID.
	 * 
	 * @param accountid
	 *            AccountID
	 */
	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}

	/**
	 * Get the AccountID.
	 * 
	 * @return AccountID
	 */
	public Integer getAccountid() {
		return this.accountid;
	}

	/**
	 * Set the FullName.
	 * 
	 * @param fullname
	 *            FullName
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * Get the FullName.
	 * 
	 * @return FullName
	 */
	public String getFullname() {
		return this.fullname;
	}

	/**
	 * Set the Email.
	 * 
	 * @param email
	 *            Email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the Email.
	 * 
	 * @return Email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the Password.
	 * 
	 * @param password
	 *            Password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the Password.
	 * 
	 * @return Password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the Phone.
	 * 
	 * @param phone
	 *            Phone
	 */
	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	/**
	 * Get the Phone.
	 * 
	 * @return Phone
	 */
	public Integer getPhone() {
		return this.phone;
	}

	/**
	 * Set the Role.
	 * 
	 * @param role
	 *            Role
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * Get the Role.
	 * 
	 * @return Role
	 */
	public String getRole() {
		return this.role;
	}

	/**
	 * Set the Status.
	 * 
	 * @param status
	 *            Status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Get the Status.
	 * 
	 * @return Status
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * Set the CreatedAt.
	 * 
	 * @param createat
	 *            CreatedAt
	 */
	public void setCreateat(Date createat) {
		this.createat = createat;
	}

	/**
	 * Get the CreatedAt.
	 * 
	 * @return CreatedAt
	 */
	public Date getCreateat() {
		return this.createat;
	}

	/**
	 * Set the set of the Booking.
	 * 
	 * @param bookingSet
	 *            The set of Booking
	 */
	public void setBookingSet(Set<Booking> bookingSet) {
		this.bookingSet = bookingSet;
	}

	/**
	 * Add the Booking.
	 * 
	 * @param booking
	 *            Booking
	 */
	public void addBooking(Booking booking) {
		this.bookingSet.add(booking);
	}

	/**
	 * Get the set of the Booking.
	 * 
	 * @return The set of Booking
	 */
	public Set<Booking> getBookingSet() {
		return this.bookingSet;
	}

	/**
	 * Set the set of the Wallet.
	 * 
	 * @param walletSet
	 *            The set of Wallet
	 */
	public void setWalletSet(Set<Wallet> walletSet) {
		this.walletSet = walletSet;
	}

	/**
	 * Add the Wallet.
	 * 
	 * @param wallet
	 *            Wallet
	 */
	public void addWallet(Wallet wallet) {
		this.walletSet.add(wallet);
	}

	/**
	 * Get the set of the Wallet.
	 * 
	 * @return The set of Wallet
	 */
	public Set<Wallet> getWalletSet() {
		return this.walletSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((accountid == null) ? 0 : accountid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Account other = (Account) obj;
		if (accountid == null) {
			if (other.accountid != null) {
				return false;
			}
		} else if (!accountid.equals(other.accountid)) {
			return false;
		}
		return true;
	}

}

