package com.btbs.model;

import java.io.Serializable;

/**
 * Model class of Admin.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Admin implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** AdminID. */
	private Integer adminid;

	/** Name. */
	private String name;

	/** Username. */
	private String username;

	/** Password. */
	private String password;

	/**
	 * Constructor.
	 */
	public Admin() {
	}

	/**
	 * Set the AdminID.
	 * 
	 * @param adminid
	 *            AdminID
	 */
	public void setAdminid(Integer adminid) {
		this.adminid = adminid;
	}

	/**
	 * Get the AdminID.
	 * 
	 * @return AdminID
	 */
	public Integer getAdminid() {
		return this.adminid;
	}

	/**
	 * Set the Name.
	 * 
	 * @param name
	 *            Name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the Name.
	 * 
	 * @return Name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the Username.
	 * 
	 * @param username
	 *            Username
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Get the Username.
	 * 
	 * @return Username
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Set the Password.
	 * 
	 * @param password
	 *            Password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the Password.
	 * 
	 * @return Password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adminid == null) ? 0 : adminid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Admin other = (Admin) obj;
		if (adminid == null) {
			if (other.adminid != null) {
				return false;
			}
		} else if (!adminid.equals(other.adminid)) {
			return false;
		}
		return true;
	}

}

