package com.btbs.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Booking.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Booking implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** BookingID. */
	private Integer bookingid;

	/** BookingDate. */
	private Date bookingdate;

	/** TotalAmount. */
	private Integer totalamount;

	/** ScheduleID. */
	private Scheduleid scheduleid;

	/** Account. */
	private Account account;

	/** The set of BookingSeat. */
	private Set<Bookingseat> bookingseatSet;

	/**
	 * Constructor.
	 */
	public Booking() {
		this.bookingseatSet = new HashSet<Bookingseat>();
	}

	/**
	 * Set the BookingID.
	 * 
	 * @param bookingid
	 *            BookingID
	 */
	public void setBookingid(Integer bookingid) {
		this.bookingid = bookingid;
	}

	/**
	 * Get the BookingID.
	 * 
	 * @return BookingID
	 */
	public Integer getBookingid() {
		return this.bookingid;
	}

	/**
	 * Set the BookingDate.
	 * 
	 * @param bookingdate
	 *            BookingDate
	 */
	public void setBookingdate(Date bookingdate) {
		this.bookingdate = bookingdate;
	}

	/**
	 * Get the BookingDate.
	 * 
	 * @return BookingDate
	 */
	public Date getBookingdate() {
		return this.bookingdate;
	}

	/**
	 * Set the TotalAmount.
	 * 
	 * @param totalamount
	 *            TotalAmount
	 */
	public void setTotalamount(Integer totalamount) {
		this.totalamount = totalamount;
	}

	/**
	 * Get the TotalAmount.
	 * 
	 * @return TotalAmount
	 */
	public Integer getTotalamount() {
		return this.totalamount;
	}

	/**
	 * Set the ScheduleID.
	 * 
	 * @param scheduleid
	 *            ScheduleID
	 */
	public void setScheduleid(Scheduleid scheduleid) {
		this.scheduleid = scheduleid;
	}

	/**
	 * Get the ScheduleID.
	 * 
	 * @return ScheduleID
	 */
	public Scheduleid getScheduleid() {
		return this.scheduleid;
	}

	/**
	 * Set the Account.
	 * 
	 * @param account
	 *            Account
	 */
	public void setAccount(Account account) {
		this.account = account;
	}

	/**
	 * Get the Account.
	 * 
	 * @return Account
	 */
	public Account getAccount() {
		return this.account;
	}

	/**
	 * Set the set of the BookingSeat.
	 * 
	 * @param bookingseatSet
	 *            The set of BookingSeat
	 */
	public void setBookingseatSet(Set<Bookingseat> bookingseatSet) {
		this.bookingseatSet = bookingseatSet;
	}

	/**
	 * Add the BookingSeat.
	 * 
	 * @param bookingseat
	 *            BookingSeat
	 */
	public void addBookingseat(Bookingseat bookingseat) {
		this.bookingseatSet.add(bookingseat);
	}

	/**
	 * Get the set of the BookingSeat.
	 * 
	 * @return The set of BookingSeat
	 */
	public Set<Bookingseat> getBookingseatSet() {
		return this.bookingseatSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bookingid == null) ? 0 : bookingid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Booking other = (Booking) obj;
		if (bookingid == null) {
			if (other.bookingid != null) {
				return false;
			}
		} else if (!bookingid.equals(other.bookingid)) {
			return false;
		}
		return true;
	}

}

