package com.btbs.model;

import java.io.Serializable;

/**
 * Model class of BookingSeat.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Bookingseat implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** BookingSeatID. */
	private Integer bookingseatid;

	/** Booking. */
	private Booking booking;

	/** Seat. */
	private Seat seat;

	/**
	 * Constructor.
	 */
	public Bookingseat() {
	}

	/**
	 * Set the BookingSeatID.
	 * 
	 * @param bookingseatid
	 *            BookingSeatID
	 */
	public void setBookingseatid(Integer bookingseatid) {
		this.bookingseatid = bookingseatid;
	}

	/**
	 * Get the BookingSeatID.
	 * 
	 * @return BookingSeatID
	 */
	public Integer getBookingseatid() {
		return this.bookingseatid;
	}

	/**
	 * Set the Booking.
	 * 
	 * @param booking
	 *            Booking
	 */
	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	/**
	 * Get the Booking.
	 * 
	 * @return Booking
	 */
	public Booking getBooking() {
		return this.booking;
	}

	/**
	 * Set the Seat.
	 * 
	 * @param seat
	 *            Seat
	 */
	public void setSeat(Seat seat) {
		this.seat = seat;
	}

	/**
	 * Get the Seat.
	 * 
	 * @return Seat
	 */
	public Seat getSeat() {
		return this.seat;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bookingseatid == null) ? 0 : bookingseatid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Bookingseat other = (Bookingseat) obj;
		if (bookingseatid == null) {
			if (other.bookingseatid != null) {
				return false;
			}
		} else if (!bookingseatid.equals(other.bookingseatid)) {
			return false;
		}
		return true;
	}

}

