package com.btbs.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Bus.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Bus implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** BusID. */
	private Integer busid;

	/** BusNumber. */
	private String busnumber;

	/** BusType. */
	private String bustype;

	/** TotalSeats. */
	private Integer totalseats;

	/** Status. */
	private String status;

	/** BusPhoto. */
	private String busphoto;

	/** The set of Passenger. */
	private Set<Passenger> passengerSet;

	/** The set of ScheduleID. */
	private Set<Scheduleid> scheduleidSet;

	/** The set of Seat. */
	private Set<Seat> seatSet;

	/**
	 * Constructor.
	 */
	public Bus() {
		this.passengerSet = new HashSet<Passenger>();
		this.scheduleidSet = new HashSet<Scheduleid>();
		this.seatSet = new HashSet<Seat>();
	}

	/**
	 * Set the BusID.
	 * 
	 * @param busid
	 *            BusID
	 */
	public void setBusid(Integer busid) {
		this.busid = busid;
	}

	/**
	 * Get the BusID.
	 * 
	 * @return BusID
	 */
	public Integer getBusid() {
		return this.busid;
	}

	/**
	 * Set the BusNumber.
	 * 
	 * @param busnumber
	 *            BusNumber
	 */
	public void setBusnumber(String busnumber) {
		this.busnumber = busnumber;
	}

	/**
	 * Get the BusNumber.
	 * 
	 * @return BusNumber
	 */
	public String getBusnumber() {
		return this.busnumber;
	}

	/**
	 * Set the BusType.
	 * 
	 * @param bustype
	 *            BusType
	 */
	public void setBustype(String bustype) {
		this.bustype = bustype;
	}

	/**
	 * Get the BusType.
	 * 
	 * @return BusType
	 */
	public String getBustype() {
		return this.bustype;
	}

	/**
	 * Set the TotalSeats.
	 * 
	 * @param totalseats
	 *            TotalSeats
	 */
	public void setTotalseats(Integer totalseats) {
		this.totalseats = totalseats;
	}

	/**
	 * Get the TotalSeats.
	 * 
	 * @return TotalSeats
	 */
	public Integer getTotalseats() {
		return this.totalseats;
	}

	/**
	 * Set the Status.
	 * 
	 * @param status
	 *            Status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Get the Status.
	 * 
	 * @return Status
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * Set the BusPhoto.
	 * 
	 * @param busphoto
	 *            BusPhoto
	 */
	public void setBusphoto(String busphoto) {
		this.busphoto = busphoto;
	}

	/**
	 * Get the BusPhoto.
	 * 
	 * @return BusPhoto
	 */
	public String getBusphoto() {
		return this.busphoto;
	}

	/**
	 * Set the set of the Passenger.
	 * 
	 * @param passengerSet
	 *            The set of Passenger
	 */
	public void setPassengerSet(Set<Passenger> passengerSet) {
		this.passengerSet = passengerSet;
	}

	/**
	 * Add the Passenger.
	 * 
	 * @param passenger
	 *            Passenger
	 */
	public void addPassenger(Passenger passenger) {
		this.passengerSet.add(passenger);
	}

	/**
	 * Get the set of the Passenger.
	 * 
	 * @return The set of Passenger
	 */
	public Set<Passenger> getPassengerSet() {
		return this.passengerSet;
	}

	/**
	 * Set the set of the ScheduleID.
	 * 
	 * @param scheduleidSet
	 *            The set of ScheduleID
	 */
	public void setScheduleidSet(Set<Scheduleid> scheduleidSet) {
		this.scheduleidSet = scheduleidSet;
	}

	/**
	 * Add the ScheduleID.
	 * 
	 * @param scheduleid
	 *            ScheduleID
	 */
	public void addScheduleid(Scheduleid scheduleid) {
		this.scheduleidSet.add(scheduleid);
	}

	/**
	 * Get the set of the ScheduleID.
	 * 
	 * @return The set of ScheduleID
	 */
	public Set<Scheduleid> getScheduleidSet() {
		return this.scheduleidSet;
	}

	/**
	 * Set the set of the Seat.
	 * 
	 * @param seatSet
	 *            The set of Seat
	 */
	public void setSeatSet(Set<Seat> seatSet) {
		this.seatSet = seatSet;
	}

	/**
	 * Add the Seat.
	 * 
	 * @param seat
	 *            Seat
	 */
	public void addSeat(Seat seat) {
		this.seatSet.add(seat);
	}

	/**
	 * Get the set of the Seat.
	 * 
	 * @return The set of Seat
	 */
	public Set<Seat> getSeatSet() {
		return this.seatSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((busid == null) ? 0 : busid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Bus other = (Bus) obj;
		if (busid == null) {
			if (other.busid != null) {
				return false;
			}
		} else if (!busid.equals(other.busid)) {
			return false;
		}
		return true;
	}

}

