package com.btbs.model;

import java.io.Serializable;

/**
 * Model class of Passenger.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Passenger implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** PassengerID. */
	private Integer passengerid;

	/** Bus. */
	private Bus bus;

	/** NRC. */
	private String nrc;

	/** Name. */
	private String name;

	/** Phone. */
	private String phone;

	/** Address. */
	private String address;

	/**
	 * Constructor.
	 */
	public Passenger() {
	}

	/**
	 * Set the PassengerID.
	 * 
	 * @param passengerid
	 *            PassengerID
	 */
	public void setPassengerid(Integer passengerid) {
		this.passengerid = passengerid;
	}

	/**
	 * Get the PassengerID.
	 * 
	 * @return PassengerID
	 */
	public Integer getPassengerid() {
		return this.passengerid;
	}

	/**
	 * Set the Bus.
	 * 
	 * @param bus
	 *            Bus
	 */
	public void setBus(Bus bus) {
		this.bus = bus;
	}

	/**
	 * Get the Bus.
	 * 
	 * @return Bus
	 */
	public Bus getBus() {
		return this.bus;
	}

	/**
	 * Set the NRC.
	 * 
	 * @param nrc
	 *            NRC
	 */
	public void setNrc(String nrc) {
		this.nrc = nrc;
	}

	/**
	 * Get the NRC.
	 * 
	 * @return NRC
	 */
	public String getNrc() {
		return this.nrc;
	}

	/**
	 * Set the Name.
	 * 
	 * @param name
	 *            Name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the Name.
	 * 
	 * @return Name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the Phone.
	 * 
	 * @param phone
	 *            Phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the Phone.
	 * 
	 * @return Phone
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the Address.
	 * 
	 * @param address
	 *            Address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Get the Address.
	 * 
	 * @return Address
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((passengerid == null) ? 0 : passengerid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Passenger other = (Passenger) obj;
		if (passengerid == null) {
			if (other.passengerid != null) {
				return false;
			}
		} else if (!passengerid.equals(other.passengerid)) {
			return false;
		}
		return true;
	}

}

