package com.btbs.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Route.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Route implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** RouteID. */
	private Integer routeid;

	/** DepartureLocation. */
	private String departurelocation;

	/** Destination. */
	private String destination;

	/** Distance. */
	private String distance;

	/** The set of ScheduleID. */
	private Set<Scheduleid> scheduleidSet;

	/**
	 * Constructor.
	 */
	public Route() {
		this.scheduleidSet = new HashSet<Scheduleid>();
	}

	/**
	 * Set the RouteID.
	 * 
	 * @param routeid
	 *            RouteID
	 */
	public void setRouteid(Integer routeid) {
		this.routeid = routeid;
	}

	/**
	 * Get the RouteID.
	 * 
	 * @return RouteID
	 */
	public Integer getRouteid() {
		return this.routeid;
	}

	/**
	 * Set the DepartureLocation.
	 * 
	 * @param departurelocation
	 *            DepartureLocation
	 */
	public void setDeparturelocation(String departurelocation) {
		this.departurelocation = departurelocation;
	}

	/**
	 * Get the DepartureLocation.
	 * 
	 * @return DepartureLocation
	 */
	public String getDeparturelocation() {
		return this.departurelocation;
	}

	/**
	 * Set the Destination.
	 * 
	 * @param destination
	 *            Destination
	 */
	public void setDestination(String destination) {
		this.destination = destination;
	}

	/**
	 * Get the Destination.
	 * 
	 * @return Destination
	 */
	public String getDestination() {
		return this.destination;
	}

	/**
	 * Set the Distance.
	 * 
	 * @param distance
	 *            Distance
	 */
	public void setDistance(String distance) {
		this.distance = distance;
	}

	/**
	 * Get the Distance.
	 * 
	 * @return Distance
	 */
	public String getDistance() {
		return this.distance;
	}

	/**
	 * Set the set of the ScheduleID.
	 * 
	 * @param scheduleidSet
	 *            The set of ScheduleID
	 */
	public void setScheduleidSet(Set<Scheduleid> scheduleidSet) {
		this.scheduleidSet = scheduleidSet;
	}

	/**
	 * Add the ScheduleID.
	 * 
	 * @param scheduleid
	 *            ScheduleID
	 */
	public void addScheduleid(Scheduleid scheduleid) {
		this.scheduleidSet.add(scheduleid);
	}

	/**
	 * Get the set of the ScheduleID.
	 * 
	 * @return The set of ScheduleID
	 */
	public Set<Scheduleid> getScheduleidSet() {
		return this.scheduleidSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((routeid == null) ? 0 : routeid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Route other = (Route) obj;
		if (routeid == null) {
			if (other.routeid != null) {
				return false;
			}
		} else if (!routeid.equals(other.routeid)) {
			return false;
		}
		return true;
	}

}

