package com.btbs.model;

import java.io.Serializable;
import java.sql.Time;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of ScheduleID.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Scheduleid implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ScheduleID. */
	private Integer scheduleid;

	/** TravelDate. */
	private Date traveldate;

	/** DepartureTime. */
	private Time departuretime;

	/** ArrivalTime. */
	private Time arrivaltime;

	/** Price. */
	private Integer price;

	/** Route. */
	private Route route;

	/** Bus. */
	private Bus bus;

	/** The set of Booking. */
	private Set<Booking> bookingSet;

	/**
	 * Constructor.
	 */
	public Scheduleid() {
		this.bookingSet = new HashSet<Booking>();
	}

	/**
	 * Set the ScheduleID.
	 * 
	 * @param scheduleid
	 *            ScheduleID
	 */
	public void setScheduleid(Integer scheduleid) {
		this.scheduleid = scheduleid;
	}

	/**
	 * Get the ScheduleID.
	 * 
	 * @return ScheduleID
	 */
	public Integer getScheduleid() {
		return this.scheduleid;
	}

	/**
	 * Set the TravelDate.
	 * 
	 * @param traveldate
	 *            TravelDate
	 */
	public void setTraveldate(Date traveldate) {
		this.traveldate = traveldate;
	}

	/**
	 * Get the TravelDate.
	 * 
	 * @return TravelDate
	 */
	public Date getTraveldate() {
		return this.traveldate;
	}

	/**
	 * Set the DepartureTime.
	 * 
	 * @param departuretime
	 *            DepartureTime
	 */
	public void setDeparturetime(Time departuretime) {
		this.departuretime = departuretime;
	}

	/**
	 * Get the DepartureTime.
	 * 
	 * @return DepartureTime
	 */
	public Time getDeparturetime() {
		return this.departuretime;
	}

	/**
	 * Set the ArrivalTime.
	 * 
	 * @param arrivaltime
	 *            ArrivalTime
	 */
	public void setArrivaltime(Time arrivaltime) {
		this.arrivaltime = arrivaltime;
	}

	/**
	 * Get the ArrivalTime.
	 * 
	 * @return ArrivalTime
	 */
	public Time getArrivaltime() {
		return this.arrivaltime;
	}

	/**
	 * Set the Price.
	 * 
	 * @param price
	 *            Price
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * Get the Price.
	 * 
	 * @return Price
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * Set the Route.
	 * 
	 * @param route
	 *            Route
	 */
	public void setRoute(Route route) {
		this.route = route;
	}

	/**
	 * Get the Route.
	 * 
	 * @return Route
	 */
	public Route getRoute() {
		return this.route;
	}

	/**
	 * Set the Bus.
	 * 
	 * @param bus
	 *            Bus
	 */
	public void setBus(Bus bus) {
		this.bus = bus;
	}

	/**
	 * Get the Bus.
	 * 
	 * @return Bus
	 */
	public Bus getBus() {
		return this.bus;
	}

	/**
	 * Set the set of the Booking.
	 * 
	 * @param bookingSet
	 *            The set of Booking
	 */
	public void setBookingSet(Set<Booking> bookingSet) {
		this.bookingSet = bookingSet;
	}

	/**
	 * Add the Booking.
	 * 
	 * @param booking
	 *            Booking
	 */
	public void addBooking(Booking booking) {
		this.bookingSet.add(booking);
	}

	/**
	 * Get the set of the Booking.
	 * 
	 * @return The set of Booking
	 */
	public Set<Booking> getBookingSet() {
		return this.bookingSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((scheduleid == null) ? 0 : scheduleid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Scheduleid other = (Scheduleid) obj;
		if (scheduleid == null) {
			if (other.scheduleid != null) {
				return false;
			}
		} else if (!scheduleid.equals(other.scheduleid)) {
			return false;
		}
		return true;
	}

}

