package com.btbs.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Seat.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Seat implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** SeatID. */
	private Integer seatid;

	/** SeatNumber. */
	private String seatnumber;

	/** Bus. */
	private Bus bus;

	/** The set of BookingSeat. */
	private Set<Bookingseat> bookingseatSet;

	/**
	 * Constructor.
	 */
	public Seat() {
		this.bookingseatSet = new HashSet<Bookingseat>();
	}

	/**
	 * Set the SeatID.
	 * 
	 * @param seatid
	 *            SeatID
	 */
	public void setSeatid(Integer seatid) {
		this.seatid = seatid;
	}

	/**
	 * Get the SeatID.
	 * 
	 * @return SeatID
	 */
	public Integer getSeatid() {
		return this.seatid;
	}

	/**
	 * Set the SeatNumber.
	 * 
	 * @param seatnumber
	 *            SeatNumber
	 */
	public void setSeatnumber(String seatnumber) {
		this.seatnumber = seatnumber;
	}

	/**
	 * Get the SeatNumber.
	 * 
	 * @return SeatNumber
	 */
	public String getSeatnumber() {
		return this.seatnumber;
	}

	/**
	 * Set the Bus.
	 * 
	 * @param bus
	 *            Bus
	 */
	public void setBus(Bus bus) {
		this.bus = bus;
	}

	/**
	 * Get the Bus.
	 * 
	 * @return Bus
	 */
	public Bus getBus() {
		return this.bus;
	}

	/**
	 * Set the set of the BookingSeat.
	 * 
	 * @param bookingseatSet
	 *            The set of BookingSeat
	 */
	public void setBookingseatSet(Set<Bookingseat> bookingseatSet) {
		this.bookingseatSet = bookingseatSet;
	}

	/**
	 * Add the BookingSeat.
	 * 
	 * @param bookingseat
	 *            BookingSeat
	 */
	public void addBookingseat(Bookingseat bookingseat) {
		this.bookingseatSet.add(bookingseat);
	}

	/**
	 * Get the set of the BookingSeat.
	 * 
	 * @return The set of BookingSeat
	 */
	public Set<Bookingseat> getBookingseatSet() {
		return this.bookingseatSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((seatid == null) ? 0 : seatid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Seat other = (Seat) obj;
		if (seatid == null) {
			if (other.seatid != null) {
				return false;
			}
		} else if (!seatid.equals(other.seatid)) {
			return false;
		}
		return true;
	}

}

