package com.btbs.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Transaction.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Transaction implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** TransactionID. */
	private Integer transactionid;

	/** Wallet. */
	private Wallet wallet;

	/** TransactionType. */
	private String transactiontype;

	/** Amount. */
	private Integer amount;

	/** TransactionNo. */
	private Integer transactionno;

	/** CreatedAt. */
	private Date createdat;

	/**
	 * Constructor.
	 */
	public Transaction() {
	}

	/**
	 * Set the TransactionID.
	 * 
	 * @param transactionid
	 *            TransactionID
	 */
	public void setTransactionid(Integer transactionid) {
		this.transactionid = transactionid;
	}

	/**
	 * Get the TransactionID.
	 * 
	 * @return TransactionID
	 */
	public Integer getTransactionid() {
		return this.transactionid;
	}

	/**
	 * Set the Wallet.
	 * 
	 * @param wallet
	 *            Wallet
	 */
	public void setWallet(Wallet wallet) {
		this.wallet = wallet;
	}

	/**
	 * Get the Wallet.
	 * 
	 * @return Wallet
	 */
	public Wallet getWallet() {
		return this.wallet;
	}

	/**
	 * Set the TransactionType.
	 * 
	 * @param transactiontype
	 *            TransactionType
	 */
	public void setTransactiontype(String transactiontype) {
		this.transactiontype = transactiontype;
	}

	/**
	 * Get the TransactionType.
	 * 
	 * @return TransactionType
	 */
	public String getTransactiontype() {
		return this.transactiontype;
	}

	/**
	 * Set the Amount.
	 * 
	 * @param amount
	 *            Amount
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * Get the Amount.
	 * 
	 * @return Amount
	 */
	public Integer getAmount() {
		return this.amount;
	}

	/**
	 * Set the TransactionNo.
	 * 
	 * @param transactionno
	 *            TransactionNo
	 */
	public void setTransactionno(Integer transactionno) {
		this.transactionno = transactionno;
	}

	/**
	 * Get the TransactionNo.
	 * 
	 * @return TransactionNo
	 */
	public Integer getTransactionno() {
		return this.transactionno;
	}

	/**
	 * Set the CreatedAt.
	 * 
	 * @param createdat
	 *            CreatedAt
	 */
	public void setCreatedat(Date createdat) {
		this.createdat = createdat;
	}

	/**
	 * Get the CreatedAt.
	 * 
	 * @return CreatedAt
	 */
	public Date getCreatedat() {
		return this.createdat;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((transactionid == null) ? 0 : transactionid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Transaction other = (Transaction) obj;
		if (transactionid == null) {
			if (other.transactionid != null) {
				return false;
			}
		} else if (!transactionid.equals(other.transactionid)) {
			return false;
		}
		return true;
	}

}

