package com.btbs.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Wallet.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Wallet implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** WalletID. */
	private Integer walletid;

	/** Balance. */
	private Integer balance;

	/** LastUpdated. */
	private Date lastupdated;

	/** PIN. */
	private Integer pin;

	/** Account. */
	private Account account;

	/** The set of Transaction. */
	private Set<Transaction> transactionSet;

	/**
	 * Constructor.
	 */
	public Wallet() {
		this.transactionSet = new HashSet<Transaction>();
	}

	/**
	 * Set the WalletID.
	 * 
	 * @param walletid
	 *            WalletID
	 */
	public void setWalletid(Integer walletid) {
		this.walletid = walletid;
	}

	/**
	 * Get the WalletID.
	 * 
	 * @return WalletID
	 */
	public Integer getWalletid() {
		return this.walletid;
	}

	/**
	 * Set the Balance.
	 * 
	 * @param balance
	 *            Balance
	 */
	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	/**
	 * Get the Balance.
	 * 
	 * @return Balance
	 */
	public Integer getBalance() {
		return this.balance;
	}

	/**
	 * Set the LastUpdated.
	 * 
	 * @param lastupdated
	 *            LastUpdated
	 */
	public void setLastupdated(Date lastupdated) {
		this.lastupdated = lastupdated;
	}

	/**
	 * Get the LastUpdated.
	 * 
	 * @return LastUpdated
	 */
	public Date getLastupdated() {
		return this.lastupdated;
	}

	/**
	 * Set the PIN.
	 * 
	 * @param pin
	 *            PIN
	 */
	public void setPin(Integer pin) {
		this.pin = pin;
	}

	/**
	 * Get the PIN.
	 * 
	 * @return PIN
	 */
	public Integer getPin() {
		return this.pin;
	}

	/**
	 * Set the Account.
	 * 
	 * @param account
	 *            Account
	 */
	public void setAccount(Account account) {
		this.account = account;
	}

	/**
	 * Get the Account.
	 * 
	 * @return Account
	 */
	public Account getAccount() {
		return this.account;
	}

	/**
	 * Set the set of the Transaction.
	 * 
	 * @param transactionSet
	 *            The set of Transaction
	 */
	public void setTransactionSet(Set<Transaction> transactionSet) {
		this.transactionSet = transactionSet;
	}

	/**
	 * Add the Transaction.
	 * 
	 * @param transaction
	 *            Transaction
	 */
	public void addTransaction(Transaction transaction) {
		this.transactionSet.add(transaction);
	}

	/**
	 * Get the set of the Transaction.
	 * 
	 * @return The set of Transaction
	 */
	public Set<Transaction> getTransactionSet() {
		return this.transactionSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((walletid == null) ? 0 : walletid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Wallet other = (Wallet) obj;
		if (walletid == null) {
			if (other.walletid != null) {
				return false;
			}
		} else if (!walletid.equals(other.walletid)) {
			return false;
		}
		return true;
	}

}

